# Site settings
title: MINIARTE
email: info@miniarte.co.mz
description: "Construção Civil & Ferragens"

# Build settings
markdown: kramdown
gems:
  - jekyll-admin
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-email-protect
  - jekyll-minifier

sass:
  sass_dir: assets/_sass
  style: compressed

port: 1212

# author
author: Ivo Zinenda
author_email: izinenda@outlook.com
author_picture: /assets/img/author/zinenda.jpg

image: /assets/img/flyer.jpg
logo: /assets/img/flyer.jpg

jekyll-minifier:
  exclude: 'sitemap.xml'

exclude:
  - vendor
  - Gemfile.lock
  - .gitignore
  - CNAME
  - debug.log

# collections
collections:
  members:
  servicos: