# Site settings
title: MiniArte
email: eduardoguta@gmail.com
description: "Construção Civil & Ferragens"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
gems:
  - jekyll-admin
  #- jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-email-protect
  - jekyll-minifier
sass:
  sass_dir: assets/_sass
  style: compressed

port: 1212

# author
author: Ivo Zinenda
author_email: izinenda@outlook.com
author_picture: /assets/img/author/zinenda.jpg

image: /assets/img/brand/logotipo.svg
logo: /assets/img/brand/logotipo.png

jekyll-minifier:
  exclude: 'sitemap.xml'

# collections
collections:
  members:
  servicos: