# Site settings
title: MINIARTE
email: info@miniarte.co.mz
description: "Construção Civil"

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-email-protect

sass:
  sass_dir: assets/_sass
  style: compressed

# author
author: Ivo Zinenda
author_email: izinenda@izitag.site
author_picture: /assets/img/author/zinenda.jpg

image: /assets/img/logotipo/blue-logo.svg
logo: /assets/img/logotipo/white-logo.svg

exclude:
  - vendor
  - Gemfile.lock
  - .gitignore
  - CNAME
  - debug.log
  - bower_components

# collections
collections:
  servicos:
  perfil:
  catalogos:
    output: true
  galeria:
    output: true

defaults:
  - scope:
      path: ""
      type: collections
    values:
      title: ""
      image: ""
      layout: page

  - scope:
      path: ""
      type: pages
    values:
      title: ""
      image: ""
      description: ""
      layout: default

  - scope:
      path: ""
      type: gallery
    values:
      title: ""
      image: ""
      images: ""
      layout: gallery