# Site settings
title: MINIARTE
email: info@miniarte.co.mz
description: "Construção Civil"

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-email-protect

sass:
  sass_dir: assets/_sass
  style: compressed

# author
author: Ivo Zinenda
author_email: izinenda@outlook.com
author_picture: /assets/img/author/zinenda.jpg

image: /assets/img/flyer.jpg
logo: /assets/img/flyer.jpg

exclude:
  - vendor
  - Gemfile.lock
  - .gitignore
  - CNAME
  - debug.log

# collections
collections:
  members:
  servicos:
  slider: