# Site settings
title: MINIARTE
email: info@miniarte.co.mz
description: "Construção Civil"
# author
author: Ivo Zinenda

# Build settings
markdown: kramdown
plugins:
  - jekyll-email-protect
  - jekyll-paginate-v2 
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-analytics


sass:
  sass_dir: assets/_sass
  style: compressed

image: /assets/img/logotipo/blue-logo.svg
logo: /assets/img/logotipo/white-logo.svg

exclude:
  - vendor
  - Gemfile.lock
  - .gitignore
  - CNAME
  - debug.log
  - bower_components
  - node_modules

# collections
collections_dir: collections
collections:
  header:
  servicos:
  perfil:
  sobre:
  produtos:
  portfolio:

jekyll_analytics: 
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-89983616-1          # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking