# Site settings
title: MINIARTE
email: info@miniarte.co.mz
description: "Construção Civil"
color: "#4183D7"

# author
author: Ivo Zinenda

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate-v2

exclude:
  - Gemfile
  - Gemfile.lock
  - bower_components
  - node_modules
  - vendor

# Collections
collections_dir: collections
collections:
  slider:
  sobre:
  perfil:
  servicos:
    output: true
  produtos:
  portfolio:

# Assets
sass:
  sass_dir: assets/_sass
  style: compressed

image: /assets/img/logotipo/logotipoMiniarte.svg
logo: /assets/img/logotipo/logotipominiartewhite.svg


jekyll_analytics: 
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-89983616-1          # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking

# Pagination Settings
pagination:
  enabled: true
  per_page: 20
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2